### ISSUE TITLE
problem when capturing a photo.

### ISSUE THREAD

**Issue by matheus-martins-developer** [quantum6/Android-USB-OTG-Camera#19]
Hello how are you? I am implementing the code and in the pic capture step, when I click I have this error, I would like to know if you know how I can solve it.

```
W/System.err: java.io.IOException: No such file or directory
W/System.err:     at java.io.UnixFileSystem.createFileExclusively0(Native Method)
W/System.err:     at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:317)
W/System.err:     at java.io.File.createNewFile(File.java:1006)
W/System.err:     at com.serenegiant.usb.USBMonitor.getDeviceList(USBMonitor.java:324)
W/System.err:     at com.serenegiant.usb.USBMonitor.getDeviceList(USBMonitor.java:301)
W/System.err:     at com.serenegiant.usb.USBMonitor$2.run(USBMonitor.java:589)
W/System.err:     at android.os.Handler.handleCallback(Handler.java:938)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err:     at android.os.Looper.loopOnce(Looper.java:226)
W/System.err:     at android.os.Looper.loop(Looper.java:313)
W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:67)
W/System.err: java.io.FileNotFoundException: /storage/emulated/0/USBCamera/failed_devices.txt: open failed: ENOENT (No such file or directory)
W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:574)
W/System.err:     at java.io.FileOutputStream.<init>(FileOutputStream.java:236)
W/System.err:     at java.io.FileWriter.<init>(FileWriter.java:113)
W/System.err:     at com.serenegiant.usb.USBMonitor.getDeviceList(USBMonitor.java:332)
W/System.err:     at com.serenegiant.usb.USBMonitor.getDeviceList(USBMonitor.java:301)
W/System.err:     at com.serenegiant.usb.USBMonitor$2.run(USBMonitor.java:589)
W/System.err:     at android.os.Handler.handleCallback(Handler.java:938)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err:     at android.os.Looper.loopOnce(Looper.java:226)
W/System.err:     at android.os.Looper.loop(Looper.java:313)
W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:67)
W/System.err: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
W/System.err:     at libcore.io.Linux.open(Native Method)
W/System.err:     at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
W/System.err:     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
W/System.err:     at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
W/System.err:     at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8529)
W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:560)
W/System.err: 	... 10 more

```

**Comment by quantum6** [comment]
It seems that the path is wrong. You can try a new path.
Good luck!

**Comment by quantum6** [comment]
You can modify FileUtils.ROOT_PATH to a valid dir.

**Comment by quantum6** [comment]
Capture a video and send to me:
quantum6@yeah.net
I will check it.
